version: '3'

services:
  db:
    image: mysql:8.0.25
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skills
      TZ: Europe/Zurich
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
