# yaml-language-server: $schema=https://schema.skills17.ch/task-config/v3/config.schema.json
id: task2
metadata:
  name: Rgb to hex
  type: js
localHistory: true
groups:
- match: .*
  displayName: Rgb to hex
  tests:
    - match: .*
      points: 1
